### ISSUE TITLE
About the Instructions how to Build Plutus

### ISSUE THREAD

**Issue by hkvb** [adacapo21/plutusPioneerProgram#3]
Hi Angelos,

In the documentation you give a number of explicit build step to be executed prior to nix-shell and the starting of the servers.
Is there a reason for this?

I simply do nix-shell, (I then build the documentation,) and then start the servers and that works fine as far as nix is concerned.
I execute these all in a nixos/nix container image as I prefer to work with containers and create a tmux session with multiple panes. (Currently test running.) My biggest headache is git coming up with unstaged files for no reason.
There is a ready-built image on Docker hub to run it: [hkvb/nixos.plutus](https://hub.docker.com/repository/docker/hkvb/nixos.plutus).

I am happy to share and discuss - the scripts I am using can be found in the plutus folder of the [hkvb/nixos.plutus] (https://github.com/hkvb/nixos.git) repository.

**Comment by adacapo21** [comment]
Hello my friend and thanks for reaching out!

Firstly, you are right, also on my side it can work only by running nix-shell in plutus repo and then I can start the server.
I don't use Docker on my side, I have found this documentation  here : 
https://docs.plutus-community.com/docs/setup/WindowsWSL.html, which is really useful for every new one here who wants to set up the environment correctly without any errors. 
Even though, I prefer to build it with only one command, believe with the commands which are referred to README, runs safely and succesfully (build all these dependencies doesn't take so much as you may think at the end).

I will add your scripts to my repository btw to give extra context, to everyone who wants to set it up your way.

**Comment by hkvb** [comment]
I am starting to have the docker image running reliably - specially when switching often between weeks. I am thinking of getting some log parsing into ElasticSearch going to make the logs a bit easier to deal with.

**Comment by adacapo21** [comment]
I added your scripts to README so everyone can see them, accordingly!
